version: "3.8"

services:
  # Overpass server API
  overpass-api:
    container_name: overpass-api
    hostname: overpass-api
    image: wiktorn/overpass-api
    restart: always
    ports:
      - "8888:80"
    environment:
      - OVERPASS_META=${OVERPASS_META}
      - OVERPASS_MODE=${OVERPASS_MODE}
      - OVERPASS_PLANET_URL=${OVERPASS_PLANET_URL}
      - OVERPASS_DIFF_URL=${OVERPASS_DIFF_URL}
      - OVERPASS_RULES_LOAD=${OVERPASS_RULES_LOAD}
    env_file:
      - .env
    depends_on:
      - nginx-proxy
    networks:
      - docker-network

  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - docker-network

# Docker Networks
networks:
  docker-network:
